package org.waterwood.waterfunservicecore.services.sys.storage;

import org.waterwood.common.CloudFSRoot;
import org.waterwood.common.io.SimpleCloudObject;
import org.waterwood.waterfunservicecore.api.resp.PresignedResp;
import org.waterwood.waterfunservicecore.api.resp.CloudResPresignedUrlResp;
import org.waterwood.waterfunservicecore.entity.audit.task.TargetType;
import org.waterwood.waterfunservicecore.utils.BizUploadPayload;
import org.waterwood.waterfunservicecore.utils.BizTargetIdPackager;

import java.io.InputStream;
import java.io.Serializable;
import java.util.List;
import java.util.Map;

public interface CloudFileService {
    /**
     * Upload a file to cloud storage
     * @param key the key ofPending the file
     * @param stream file input stream {@link InputStream}
     * @param size file size
     * @param contentType file content type
     */
    @Deprecated
    void uploadFile(String key, InputStream stream, long size, String contentType);
    /**
     * Get file from cloud storage
     *
     * @param root root key of cloud storage, which act as the first level key for cloud storage
     * @param path    url path
     * @param bizId   business id, which act as cache key for cache store
     * @param resType resource type
     * @return direct url which can be used to access the file
     */
    CloudResPresignedUrlResp getReadUrlCached(CloudFSRoot root, String path, Serializable bizId, TargetType resType);

    /**
     * Build put policy with business key
     *
     * @param root    root key of cloud file service
     * @param path    path of the resource must contain, Usually generate by{@link org.waterwood.waterfunservicecore.utils.CosKeyPathGenerator}
     * @param payload packaged biz target id, Usually generated by{@link BizTargetIdPackager}
     * @return Presigned request response contains the url and key for file upload, and the key will be used for file access after upload success.
     */
    PresignedResp buildPutPolicyWithPayload(CloudFSRoot root, String path, BizUploadPayload payload);

    /**
     * Build put policy with business key with key root = {@link CloudFSRoot#UPLOADS}
     * also see {@link #buildPutPolicyWithPayload(CloudFSRoot, String, BizUploadPayload)}
     * @param path    path of the resource must contain, Usually generate by{@link org.waterwood.waterfunservicecore.utils.CosKeyPathGenerator}
     * @param payload packaged biz target id, Usually generated by{@link BizTargetIdPackager}
     * @return Presigned request response contains the url and key for file upload, and the key will be used for file access after upload success.
     */
    PresignedResp buildPutPolicyForUploads(String path, BizUploadPayload payload);

    /**
     * Batch build put policy with business key with key root = {@link CloudFSRoot#UPLOADS}
     *
     * @param paths    List paths of the resource must contain, Usually generate by{@link org.waterwood.waterfunservicecore.utils.CosKeyPathGenerator}
     * @param payloads packaged biz target id, Usually generated by{@link BizTargetIdPackager}
     * @return List of Presigned request response contains the url and key for file upload, and the key will be used for file access after upload success.
     */
    List<PresignedResp> batchBuildPutPolicyForUploads(List<String> paths, List<BizUploadPayload> payloads);

    /**
     * Remove file from cloud storage
     *
     * @param root
     * @param key  the key ofPending the file
     */
    void removeFile(CloudFSRoot root, String key);

    /**
     * Batch get file from cloud storage
     * <b>BizIds</b> must correspond with paths
     *
     * @param rootKey     cloud resource key root
     * @param paths        url paths
     * @param bizIds       business ids
     * @param cloudResType resource type
     * @return map of Pending direct url which can be used to access the file,
     *         null value in map means the file is not exist or failed to get url,
     *         or paths is null, and the key of map is the bizId provided in parameter.
     */
    <ID extends Serializable> Map<ID, CloudResPresignedUrlResp> batchGetReadPublicUrlCached(CloudFSRoot rootKey, List<String> paths, List<ID> bizIds, TargetType cloudResType);

    String getCachedRedisKey(Serializable bizId, TargetType resType, CloudResOperationType operationType);


    /**
     * Detect cloud file type by file's magic number, and check if the file type is matched with asserted cloud file type.
     *
     * @param KeyPath       cloud file key path
     * @param cloudFileType asserted cloud file type.
     * @return simple object contains cloud file info, such as content type and size with key.
     * @throws org.waterwood.common.exceptions.BizException if the cloud file type is not matched.
     */
    SimpleCloudObject detectAndAssertCloudFile(String KeyPath, CloudFileType cloudFileType);

    /**
     * Copy file from origin path to target path, and remove the old file.
     * @param originalRoot original root key path
     * @param originPath original path
     * @param targetRoot target cloud root key
     * @param targetPath target Path
     */
    void copyFileAndRemoveOld(CloudFSRoot originalRoot, String originPath, CloudFSRoot targetRoot, String targetPath);

    /**
     * Clear file get cache
     * @param bizId business id
     * @param targetType resource type
     */
    void clearGetCache(Serializable bizId, TargetType targetType);

    /**
     * Parse String type biz payload
     * @param token upload token
     * @return String ID payload
     */
    BizUploadPayload parseToken(String token);


}
