/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseDialog: typeof import('./components/BaseDialog.vue')['default']
    CaptchaDialog: typeof import('./components/CaptchaDialog.vue')['default']
    CardContainer: typeof import('./components/CardContainer.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTag: typeof import('element-plus/es')['ElTag']
    IconComponent: typeof import('./components/IconComponent.vue')['default']
    ImagePreviewDialog: typeof import('./components/ImagePreviewDialog.vue')['default']
    ListPage: typeof import('./components/ListPage.vue')['default']
    PlainTableContainer: typeof import('./components/PlainTableContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchContainer: typeof import('./components/SearchContainer.vue')['default']
    SingleImageUploader: typeof import('./components/SingleImageUploader.vue')['default']
    TableContainer: typeof import('./components/TableContainer.vue')['default']
  }
}
